# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

parameters:
  - name: testval1
    type: string
    default: testvalparam

  - name: testval2
    type: number
    values:
      - 1
      - 2
      - 3

pool:
  vmImage: ubuntu-latest

steps:
- checkout: none
- download: none
- script: echo Hello, world! Params are @pipeline().parameters.testval1
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

